### ISSUE TITLE
Namensauflösung

### ISSUE THREAD

**Issue by nico-osd** [nico-osd/osd_repo#1]
Brauchen wir einen DNS Server oder machen wir die Namensauflösung manuell (hosts-Datei)?

**Comment by LarsHeins** [comment]
Testantwort

**Comment by LarsHeins** [comment]
Soda, mein Vorschlag wir arbeiten mit einem lokalen DNS Server, um die Raspberries im Clusterbetrieb auf der FH mit variablen IP Adressen zu finden. Dieser Server kann dann bei Bedarf auch gleich Timeserver spielen, falls das notwendig sein sollte. D.h. wir können für PyCharm einen fixen Namen vergeben, der in der FH über den DNS Server aufgelöst wird und für daheim würde ich die Hosts Datei verwenden. An der Anleitung für die Hosts Datei arbeite ich gerade. danach würd ich mir ansehen, wie komplex das ist nen DNS auf nem Pi zum Laufen zu bringen...
LG L.

**Comment by LarsHeins** [comment]
Im Zuge der Anleitung für die Hosts Datei stellt sich mir die Frage welchen Domain Namen wir für unser Projekt intern verwenden. Denn es macht ja Sinn den Raspberry daheim im LAN genauso zu zu benennen wie auf der FH. Ich schlage mal den Namen "oec.local" vor. Ich bitte um Feedback! Thx L.

**Comment by nico-osd** [comment]
Also ein Namensschema à la "nicoPi.oec.local". Finde ich prinzipiell gut, wissen wir bereits ob der Router das unterstützt bzw. haben wir die genaue Bezeichnung, @wrogner?

**Comment by LarsHeins** [comment]
Naja ich wollt mich darum kümmern, dass auf einem rasp nen dns installiert wird. Dann können wir eh spielen. Das der dann nur ein single und kein cluster ist soll uns ja im labor betrieb nicht stören. Wenn jemand allerdings 96 stunden tage hat und nicht einschlafen kann, dann is derjenige eingeladen sich am ende des projekts auch darum noch zu kümmern! ;)
LG L.

**Comment by wrogner** [comment]
Der Router ist ein WRT624v3. Er kann DHCP providen und DNS forwarden (aber nicht selbst hosten).

Wenn das notwendig sein sollte, dann müssten wir uns um einen anderen Router kümmern.
Ich habe aktuell keinen leer herumstehenden Router (ausser einen zweiten WRT624v3)

lg

**Comment by wrogner** [comment]
Um hier nicht sinnlos auf irgendwas zu warten würde ich definieren:

Wir brauchen DHCP mit Namensvergabe und DNS.
Bis das erledigt ist: Fixe Namen als Hostname und IP vergeben und in der Hosts-datei diese und die IP eintragen.
Kann per Git ausgetauscht werden.

**Comment by nico-osd** [comment]
Durch Diskussion am 26.11.2015 auf Broadcasting geeinigt - DNS ist vorerst aus dem Rennen.
