### ISSUE TITLE
Yoyo Algorithmus für Leader Election (FYI)

### ISSUE THREAD

**Issue by wi13b071** [nico-osd/osd_repo#2]
[yoyo.pdf](https://github.com/nico-osd/osd_repo/files/34182/yoyo.pdf)

Als Nachtrag zum Forumspost auf Moodle: Anbei eine detaillierte Beschreibung/Dokumentation des Yoyo-Algorithmus. 

Vorteile:
-) Kann basierend auf jeder arbiträren Netzwerk-Topologie gestartet werden
-) Metrik für Auswahl kann variieren, wir würden aber vom aktuellen Standpunkt aus bei den IP-Adressen bleiben (mit Team Wetzlmayer/Twrdy abgestimmt)
-) Vom Ablauf leicht verständlich (zwecks weiterer Umsetzung)

Nachteile:
-) relativ hoher Kommunikationsaufwand zwischen Knoten

Wird von uns bedacht:
Der Yoyo-Algorihmus beinhaltet per Definition keinen Alternativablauf, für den Fall, dass der initial gewählte Leader plötzlich nicht mehr erreichbar ist. Wir haben hier vor, eine entsprechende Eskalation (bspw. inspiriert durch den Bully-Algorithmus) hinzuzufügen, die für solche Fälle "einspringt" und eine erneute Election mit den übrigen Knoten startet.

**Comment by nico-osd** [comment]
Habt ihr die folgenden Fragen schon diskutiert:

- Was genau ist der Outcome von Markus und Christoph (Gruppe 1)?
- Kennen sich alle Knoten bereits?
- Was wissen die Knoten von einander nach dem ersten Schritt?

Ich kann nicht einschätzen wie gut sich der Algorithmus für uns eignet, wie
seht ihr das?
Am 13.11.2015 6:22 nachm. schrieb "wi13b071" <notifications@github.com>:

**Comment by LarsHeins** [comment]
Hello,
wir haben uns entschieden den RANFT Algorithmus zu nehmen. Ist wesentlich einfacher zu verstehen, zu anderen Gruppen abzugrenzen und vor allem: der Master wechselt nach einer Election nur dann, wenn der aktuelle Master verstirbt, er keine Mehrheit mehr hat oder beim Beitritt eines neuen Clustermitglieds. Hier eine nette Erklärung dazu: https://www.youtube.com/watch?v=YbZ3zDzDnrw . Was wir allerdings brauchen ist eine Art Datenbank in der sich (neue) Mitglieder registrieren können. und halt einen Prozess dazu der auch beinhaltet, wie sich die Mitglieder finden. Nachdem wir wahrscheinlich eh nen DNS Server brauchen ergibt sich die Frage, ob wir für das "finden des Clusters" nicht auch mit einem DNS Eintrag arbeiten können, der dynamisch vom ersten Knoten gesetzt wird, solange kein solcher DNS Eintrag vorhanden ist. Der aktuelle Master könnte diesen Eintrag ja immer mit sich nehmen. Ist aber nur eine Idee. Ich bitte hierzu um Feedback - vor allem von Team1 !!! ;)
Thx L.

**Comment by christw92** [comment]
@LarsHeins wie du schon erwähnt hast, beim DNS Server hätten wir das Problem des Single point of failures.
Das hätten wir bei kontinuierlichem Multicast/Broadcast nicht. Wenn jeder Knoten alle x Sekunden eine Nachricht(Name?) an die Multicast-Adresse sendet und zusätzlich ständig zuhört, welche Nachrichten von anderen Knoten an diese Multicast-Adresse gesendet werden. Die IP-Adressen der Knoten wären somit jedem der Knoten untereinander bekannt.

Hier ein Link zu einem Bsp. für das Senden und Empfangen von Multicasts in Python: (schon ausprobiert)
https://pymotw.com/2/socket/multicast.html

Aber wir können natürlich auch die Variante mit DNS-Eintrag verwenden, wenn wir den DNS Server sowieso benötigen. Ich verstehe aber nicht wie genau das funktionieren soll (dynamisch vom ersten Knoten gesetzter DNS-Eintrag usw.) Kannst du das vielleicht nochmal genauer erklären? :)

**Comment by LarsHeins** [comment]
Dieser SOF hat aber nicht wirklich was mit unserem projekt zu tun. Wir haben ja auch kein redundantes netz etc. und wie ein dns cluster funktioniert muessen wir auch nicht neu erfinden. Da gibts genug literatur zu. Ob ein client zusätzlich nen A Record registrieren kann weiss ich nicht - müssten wir testen. Is auch nur ne idee... ;)

**Comment by nico-osd** [comment]
Durch die Diskussion letzte Woche bleibt weiterhin die Frage nach dem "richtigen" Master Election Algorithmus. Habt ihr euch final auf RAFT geeinigt? Dann ist das nächste Ziel einen Prototypen zu entwickeln und mit diesem weiter zu arbeiten.

Zum Nachschlagen schreibe ich hier erneut das Big Picture im Bezug auf die Liste, welche alle Knoten besitzen müssen, aus meiner Erinnerung nieder.

Der Output von ```Broadcasting``` (BC) ist, wie in der Readme.md ersichtlich, ein Liste mit allen im Netzwerk befindlichen Knoten:

| IP                 | 
|------------------|         
|```10.x.x.1 ``` |
|```10.x.x.12```|
|```10.x.x.15```|
|```10.x.x.11```|
|```10.x.x.5```  |
|```...```|

Nach der ```Master Election``` (ME) wird diese um eine Spalte erweitert:

| IP                |  Is Master? (T/F) |
|-----------------|-----------------------|
|```10.x.x.1 ```| ```F```                 |
|```10.x.x.12```| ```T```                |
|```10.x.x.15```|```F```                 |
|```10.x.x.11```|```F```                 |
|```10.x.x.5```  |```F```                 |
|```...```|          ```...```                 |


Mit dem ```Distribute Exercise``` (DE) Paket wird die Liste erneut erweitert:

| IP                 |  Is Master? (y/n) | Name                   | Pyro-URI                                       |
|------------------|-----------------------|-------------------------|----------------------------------------------|
|```10.x.x.1 ``` | ```F```                 | ```Ferdi```              | ```PYRO:xxx@10.x.x.1:48452```   |
|```10.x.x.12```| ```T```                 | ```Karli```               | ```PYRO:yyy@10.x.x.12:19432``` |
|```10.x.x.15```|```F```                  | ```Franzi```            | ```PYRO:zzz@10.x.x.15:52432``` |
|```10.x.x.11```|```F```                  | ```Poldi```              | ```PYRO:aaa@10.x.x.11:28432``` |
|```10.x.x.5```  |```F```                  | ```Uschi```             | ```PYRO:bbb@10.x.x.5:47432```   |
|```...```           |```...```                  | ```...```                   | ```...```                                            |


Die Pyro URI steht noch zur Diskussion. Laut unserer letzten Definition haben alle Knoten diese Liste.

Ich bitte um eure Kommentare und möchte diese Diskussion wiederbeleben.

**Comment by wrogner** [comment]
Geht es immer noch um Master Election?

Wenn obige Liste auf allen Knoten bekannt ist, kann doch der Knoten mit der geringsten/höchsten IP zum Master werden. Das ist leicht prüfbar
'''getListOfIPs
sortListOfIPs
compare myIP == minIP:
   setMaster(self)
'''

Dazu gibt es mehrere Fragen:
1. zu Beginn wird es eine Update Storm an IPs geben. Wie geht man damit um
2. wie erkennt man, dass der Master weg ist?
3. wie erkennt man Partitionierung? Ist das im Moment notwendig?
4. wie erkennt man, dass ein neuer potentieller Master ins Netz gekommen ist?
5. wie erfolgt das Handover?

**Comment by wi13b071** [comment]
Vom aktuellen Standpunkt aus sind weder der Yoyo Algorithmus, noch der Raft Algorithmus geeignet, um den notwendigen Sachverhalt darzustellen. Beide sind, wie Herr Rogner sagt, überdimensioniert und für wesentlich komplexere Netzwerktopologien geeigneter als für das, was wir vorhaben. Wir hätten beide schon vor der Abstimmung nicht in deren vollem Umfang, sondern im besten Fall nur teilweise anwenden können, da die Algorithmen selbst schon Aufgaben der Gruppe 1 abgedeckt hätten. Nach der Abstimmung von letzter Woche ist unsere initiale Vorstellung von unseren Aufgaben dann weiter geschrumpft, was die beiden Vorgehensweisen noch unpassender gemacht hat.

Unser momentanes Vorhaben: Anhand der Liste, die uns Broadcasting (BC) zur Verfügung stellt, soll das Pi mit der höchsten (oder niedrigsten, das ist einerlei) IP als Master gewählt werden, da 
a) das die einfachste Variante ist, weil die Daten schon vorhanden sind
b) es aus unserer Sicht keinen Sinn macht, eine andere Auswahlmetrik zu definieren, wenn diese sich schon anbietet.

Über die genannten Probleme von Herrn Rogner haben wir teilweise schon diskutiert:

Zu 2) Sehen wir ähnlich. Broadcasts sehen wir als aufwändig in Sachen Kommunikation, teamintern haben wir uns aber darauf geeinigt, das vorerst in Kuaf zu nehmen.

Zu 4 und 5) Das sind Probleme, die wir vor der letztwöchigen Abstimmung am Radar hatten, die wir aber nach letzter Woche eher in Broadcasting (BC) angesiedelt sehen, da sich der Master Election Prozess an sich nicht ändert, wenn ein definierter Master wegfällt oder ein potentieller neuer Master hinzukommt. Broadcasting (BC) hat aber unserem Verständnis des neue Big Pictures nach bereits die Möglichkeiten, diese Infos (Wer ist neu im Netz? Ist alter Master noch aktiv?) abzufragen und zu verarbeiten.

Eine Frage, die man sich stellen sollte: Ist Master Election (ME) in Umfang und Komplexität einem separaten Modul gleichzustellen?

**Comment by nico-osd** [comment]
> Wenn obige Liste auf allen Knoten bekannt ist, kann doch der Knoten mit der geringsten/höchsten IP zum Master werden.

Ich habe das Gefühl, dass Ihre Aussagen mehr akzeptiert als kritisch hinterfragt werden. Deswegen mache ich einen anderen Vorschlag:

Bei Startup des Programms:
```python
my_startup = int(time.time())
```

Sobald die Liste mit IP-Adressen mind. 2 Einträge besitzt, "tauschen" diese die Startuptime aus und vergleichen:
```python
master = -1

for time in time_list:
    master = my_startup if my_startup < time else time
```


> Eine Frage, die man sich stellen sollte: Ist Master Election (ME) in Umfang und Komplexität einem separaten Modul gleichzustellen?

Meiner bisherigen Auffassung nach ist in ME genug zu tun, siehe Fragen von @wrogner. Diese Fragen sollten in dem ME Modul beantwortet werden. Für mich macht es bisher keinen schlanken Schuh, dass wir BC mit Funktionalitäten aufblasen.

Gerade die Fragen 4 & 5 sind ziemlich spannend im Zusammenhang mit der Master Election per min(IP). Jeder hinzukommende Knoten ist potenzieller Master. Um die Fragen 1 & 2 werden wir nicht herumkommen und spätestens hier sehe ich die Notwendigkeit eines eigenen Moduls gegeben.

Damit ich nicht nur herumnörgel:

Zu Frage 2 von @wrogner:
1. Möglichkeit: Der Master sendet regelmäßig Keep Alive Pakete an die Knoten in der Liste.
2. Möglichkeit: Der Master hat offene TCP-Verbindungen zu den Knoten, sobald diese abbricht und nicht wiederhergestellt werden kann war er einmal Master.
3. Möglichkeit: Broadcasts.
4. Möglichkeit: Die Knoten senden in versetzten Zeitintervallen pings an den Master, falls dieser nicht erreichbar ist ...

__ToDo__: Besprechen dieser Problematik mit der BC-Gruppe, da diese die Implementierung der Netzwerk-Kommunikation übernimmt.

> 3. wie erkennt man Partitionierung? Ist das im Moment notwendig?

Was verstehen Sie unter "Partitionierung"?

--
Nico

**Comment by fg-devs** [comment]
Zu Frage 3 (Partitionierung) von @wrogner:

Bei der letzten Lehrveranstaltungseinheit meinten Sie, dass wir die Partionierung nicht beachten müssten, da dies zu kompliziert sei. Deshalb würde ich vorschlagen bzw. wie Sie schon erwähnt haben, dass wir die Partitionierung vorerst weglassen.

**Comment by nico-osd** [comment]
Da YoYo als Leader Election raus ist - closed.
