### ISSUE TITLE
Frage zum Thema Listen bzw. Speichern von Teilnehmern

### ISSUE THREAD

**Issue by weltvonalex** [nico-osd/osd_repo#3]
Hello, ich würde eure Hilfe brauchen.  Unser Thema ist das Speichern der Teilnehmer bzw. das Speichern einer History.  

Wie geht mein Team das an. Paar Ideen hätte ich aber ich komme mit denen nicht auf einen grünen Zweig. 

1. Idee
Jeder Raspy hat seine eigene in sich geschlossene Datenbank. 
Diese DB überträgt ihre Daten in Intervallen an alle anderen Raspy's. 
Vorteil: Jeder Knoten steht für sich alleine da 
Nachteil: Wie komme ich an die Liste der anderen Rechner. Sehr hoher traffic weil die DB's vor sich hin broadcasten. Wenn ein Raspy ausfällt noch bevor er die Daten übertragen hat sind die Daten verloren. 

2. Idee
Jeder Raspy ist Teil einer großen DB, zusammen ergeben die eine große Datenbank bzw. eine logische DB Einheit. 
Vorteil: Ausfalls-sicherer weil der Nachbarknoten einspringt. 
Nachteil: ... jeder Client muss in den Verband eingebunden werden außer man kann das vorkonfigurieren?
Wie finden sich die Datenbanken - hier kommen wir wieder zur Liste. 

3. Idee 
Master hat alle Daten, er hat 2 Backup Server mit denen er Synct. Fällt der Mastere aus, wird ein neuer Master gewählt. Dieser neue Mastererhält dann von den Backups die Daten. Falls nicht einer von ihnen der Master wird. 
Vorteil:
Nachteil: Ist nur eine Idee, hätte keine Vorstellung wie ich das umsetzte

4. Idee
Wir hängen eine Raspy an den Dns bzw. bezieht er vom DNS die Daten aber dann ist das wieder eine Einzellösung. 

Hauptthema ist wie ich zur der Liste komme und ob es besser ist eine Distributed Datenbank zu haben oder einzelne Inseln.

Als Produkte hätte ich -->

OrientDB - eine Graphen DB die auch clustern kann. 
Vorteile: Laut Datenblatt erfüllt die die Vorrausetzungen, wäre Graphen basiert, NoSql (Hab ich unter den Vorteilen weil es mal was anderes wäre bzw. ich hatte mit sowas noch nicht zu tun) 
Nachteil: vielleicht für das Projekt ein overkill? 
Link: http://orientdb.com/why-orientdb/

Apache Cassandra - klingt auch sehr ansprechend 
Vorteile: Jeder Knoten hat die gleiche Rolle, Apache License (version 2.0). 
Scalierbar, Fehler-Tolerant (daten werden automtische zu verschiedenen Knoten repliziert) , ausgefallene Knoten werden ohne Downtime ersetzt 
Nachteil: ----
Link: http://cassandra.apache.org/

Hier noch Kandidaten aber da muss ich noch mehr recherchieren. 

Oracle RCA: 
Cluster Lösung von Oracle, habe noch nicht so viele Daten dazu. 

MySQL Cluster:
Siehe Oralce, muss noch nachforschen. 

Mongo DB:

**Comment by nico-osd** [comment]
Hey Alex,

sieht nach einer Menge Recherche aus, die du/ihr betrieben hast/habt, Hut
ab!

Soweit ich das verstanden habe, ist es im ersten Schritt nicht erforderlich
eine Datenbank zu benutzen. Natürlich ist es ein hoch gesteckte Ziel und
ich möchte deine bzw. eure Arbeit nicht schmälern. Nur stellt sich mir die
Frage, ob das gleich zu Beginn nicht zu viel ist.

----

Was ich als erstes Ziel verstanden habe:

- Speichern der Namen der (aktiven) Knoten

Da würde sich im ersten Schritt eine Key-Value basierte Speicherarchitektur
(Dict) anbieten.

Sobald wir den Schritt gemeistert haben, können wir uns mit möglichen
Erweiterungen bzgl. Speicherung, Protokollierung, Verteilung etc. Gedanken
machen.

Was sagt dein Team (Bernhard & Bianca) zu deinen Ideen? Bzw. wollt ihr von
Beginn an eine verteilte DB einsetzen? Was genau wollen wir speichern?

Wie seht ihr das?
Am 19.11.2015 10:56 vorm. schrieb "weltvonalex" <notifications@github.com>:

**Comment by weltvonalex** [comment]
Kämpfe mit der gleichen Frage, Hr. Rogner hat mal das Wort Datenbank fallen lassen und in meiner Pitbull Mentalität hab ich mich gleich mal darin verbissen . (an der Schwäche arbeite ich aber ). 

Dachte ich mir ich steige mal aus meinem Denkgraben und frage euch, manchmal sieht man die einfachen Lösungen einfach nicht. 

Ich hätte auch kein Problem damit ein TXT File zu schreiben das einfach alle Einträge hat, quasi als poor mans log.  
Oder die Infos vom DNS zu beziehen aber da kommt es drauf an wie und ob er kommt. :)

**Comment by hardbern** [comment]
also mir geht es ähnlich ... verteilte db: ja, schön und gut, aber für eine liste von ein paar computern ? vor allem: wenn es einen dns-server gibt, dann gibt es ja schon die information, welcher raspi welche ip hat - das bedeutet man bräuchte ja nur noch diese einträge abholen oder verteilen. das stellt aber auch ein paar andere dinge in frage: master selection ... master selection wovon ? . ich denke, ohne eine gemeinsame vorgehensweise und einem allgemeinen verständnis ALLER teams zur vorgehensweise wirds schwierig. also: wird es DNS geben ? wenn ja, bräuchte es keinen master-raspi sondern alle raspis holen sich die liste vom DNS (der halt dann eine art master funktion hätte) ab. es müsste dann noch einen backup-DNS geben.  bei verteilter db wäre ich auf "hypertable" gestossen, eine noSQL db die u.a. auch python-API anbietet (und das soll ja auch mit ein sinn unserer übung sein) . ich bin zu wenig entwickler um beurteilen zu können, ob der "provisorische" pfad, der eingeschlagen wurde, für die entwicklung der "echten" lösung hilfreich sein kann oder ob dann ohnehin wieder von vorne begonnen werden muss (s. dynamische master election, verzicht auf dns, verteilte db ?). das wären jetzt einmal so meine gedanken dazu. lg bernhard

**Comment by nico-osd** [comment]
Bitte widersprecht mir, falls ich im folgenden etwas falsches behaupte. Das
ist meine ehrliche Meinung und ich möchte die Diskussion damit nicht
ersticken.

--

Du sprichst wichtige Punkte an und so wie ich es verstanden habe ist es
Sinn dieser LV, dass wir nicht _einmal_ coden und ein fertiges Produkt
haben. Sondern viel eher der Entwicklungsprozess. Sprich ändernde
Anforderungen/Schnittstellen, daraus resultierendes Refactoring und
schließlich die Zusammenarbeit in einem verteilten Team.

Aus dem Grund bin ich der Meinung, dass die Denkanstöße von Herrn Rogner
mit einer guten Absicht gegeben wurden. Die derzeitigen Anforderungen sehe
ich im Kontrast dazu stehend. Denn eine verteilte Datenbankarchitektur zu
verstehen, zu implementieren und zu testen dauert bei weitem länger als
Informationen in ein Dict zu speichern.

Die Verwendung eines DNS Servers ist ein guter Hinweis. Solange wir keinen
haben, würde ich nicht darauf vertrauen, dass es diesen jemals gibt. No
offense.

Widersprich mir, falls ich das Ziel für eure Gruppe falsch formuliere:

Liste der Namen der (aktiven) Knoten erstellen und verwalten.

Genau das und nicht mehr (DNS, Distr. DB, etc.) ist gefordert. In
Anbetracht der fortschreitenden Zeit, würde ich dazu raten, dass wir uns
auf die derzeitigen Anforderungen konzentrieren. Da gibt es genug Themen,
welche auf eine Lösung warten.

Nico
Am 19.11.2015 2:07 nachm. schrieb "hardbern" <notifications@github.com>:

**Comment by wrogner** [comment]
Think simple:

Python bietet ooB Dictionaries an. { key:value, key:value, ...}
Per JSON kann ich diese Struktur abspeichern und wieder hereinladen.

Ist eine poor mans database.

Alternative:
sqlite3 installieren
create table
insert into table ...

Ist eine small track database (Schmalspurdatenbank, wie der Österreicher zu sagen plfegt)

**Comment by wrogner** [comment]
In irgend einem Posting hat Nico Henglmüller die Grundintention schon gut auf den Punkt gebracht:

Es geht darum, anhand der Problemstellungen die wesentlichen Aspekte der OSS SW-Entwicklung zu erkennen und auszuprobieren.

Wo wir nicht weiterkommen mit der Hardcore Variante, bauen wir uns einfach Stubs.

Lassen Sie bitte den Studenten des nächsten Jahres noch was übrig ;-)

**Comment by nico-osd** [comment]
Siehe Readme.md auf der Startseite.

Nico
