### ISSUE TITLE
Zu unserer Diskussion am Do. - Callback

### ISSUE THREAD

**Issue by wrogner** [nico-osd/osd_repo#5]
Wir haben uns am Do. u.a. über Callbacks unterhalten.
Eine saubere Implementierung wäre, ein Observer-Pattern einzuführen.
Ich habe kurz was zusammengeschrieben, das ich gerne teilen möchte. Kommentare, Kritik und Verbesserungen sind erwünscht:
(Das .txt muss entfernt werden)

[observer.py.txt](https://github.com/nico-osd/osd_repo/files/53167/observer.py.txt)

Diese Datei ist auch unter examples zu finden.

**Comment by nico-osd** [comment]
Sie verwenden anscheinend gerne eine Programmiersprache, in welcher Strichpunkte das Statement beenden - ich habe sie entfernt.

Ich lege uns allen folgende Dokumentationen ans Herz:

> [PEP8](https://www.python.org/dev/peps/pep-0008/): für Codingconventions in Python
> [PEP257](https://www.python.org/dev/peps/pep-0257/): Commentconventions
> [PEP3119](https://www.python.org/dev/peps/pep-3119/) & [Abstract Base Classes](https://docs.python.org/3/library/abc.html) zu Abstract Base Classes ans Herz, da diese hier definitiv notwendig sind. Siehe [dbader](https://dbader.org/blog/abstract-base-classes-in-python)

In unserem Fall sind Methoden Dokumentationen dringend notwendig, da die Methoden möglicherweise nicht in dem Intentionen des federführenden Coders verwendet wird. Durch die Kommentare wird sichergestellt was die Vorbedingung ist und was die Nachbedingung ist (falls diese nicht explizit überprüft werden).

Zu dem Observer-Pattern:

> Es gibt Youtube Videos dazu
> [Java ist auch eine Insel] (http://openbook.rheinwerk-verlag.de/javainsel/javainsel_10_002.html)

**Comment by wrogner** [comment]
Uups. Naja, Python ignoriert die ; am Ende der Zeile, aber danke für den Hinweis.

**Comment by nico-osd** [comment]
Da ich gestern nicht zur näheren Betrachtung gekommen bin, hole ich dies heute nach. Folgende Fragezeichen haben sich bei mir nach dem Code-Review aufgetan:

* Welche Funktion hat das Attribut `Observer._observed`? Es wird in der Klasse nicht verwendet, sondern immer per Parameter übergeben.
* Definition von Konstruktoren in Interfaces oder ABC sind mMn nicht notwendig, ich habe diese entfernt.
* Ist nicht Threadsafe.

Die synchronized Implementierung von Peter Norvig und die Kombination mit dem Observer-Pattern scheint mir naheliegend, wie in [Threadsafe Observer](http://python-3-patterns-idioms-test.readthedocs.org/en/latest/Observer.html) beschrieben.

Falls sie das Interface meinen, welches überschrieben wird, ist dies mit folgendem CodeSnippet berücksichtigt worden:

```java
interface Observer<T>
{
  public void update( Observable<T> o, T arg );
}
```

dies unterscheidet sich nicht von der Lösung in python:

```python
class ObserverInterface(metaclass=ABCMeta):
    """Observer pattern: Observer interface"""

    @abstractmethod
    def update(self, observable, arg):
        pass
```

**Comment by nico-osd** [comment]
Ist bereits mit Anpassungen innerhalb des BC-Moduls in Verwendung - closed.
