### ISSUE TITLE
MasterElection: listhandler.Entry issues

### ISSUE THREAD

**Issue by nico-osd** [nico-osd/osd_repo#7]
> we thought about iterating over all entries to set all is_master-attributes to false, but this is not possible due to the current implementation of util.listhandler - Entry

Um was genau geht es?

**Comment by PetraKue** [comment]
Wir hätten überlegt, vor dem Setzen des is_master-Attributs beim neuen Master sicherzustellen, dass kein Eintrag als Master deklariert ist bzw. alle dahingehend zu ändern um erst danach dem neu gewählten Master das Attribut auf true zu setzen. Das geht aber nicht, aufgrund des is_master-Setters, der den Wert nur zuweist, wenn er nicht auf true steht --> siehe code-copy. Was war deine Intention dahinter? Braucht jemand das so?
 @is_master.setter
    def is_master(self, value):
        if not self._is_master:
            self._is_master = value

LG, Team ME :-)

**Comment by nico-osd** [comment]
Mein Gedankengang war:

1. ListHandler wird durch Main erstellt
2. BC füllt IPs mit leeren Entry Objekten => handler.add_or_override_entry(ip, Entry())
3. ME setzt einmalig is_master = True

Für mich war folgendes als gegeben definiert:
* Wenn ein Entry als Master definiert wird, kann sich dies nicht mehr ändern, da der Eintrag mit Hilfe des ListHandlers entfernt werden muss. (Ein Master kann nur durch das sterben abgewählt werden, einmal definiert - nicht mehr änderbar)
* Oder anders: Wenn ein Master einmal Master ist, dann kann er nur durch das entfernen des Key-Value-Pairs aus dem listhandler nicht mehr master sein.

**Comment by wi13b071** [comment]
Danke für die Erläuterung - wir haben heute entsprechende Anpassungen gemacht in welchen wir auf unseren initialen Ansatz verzichtet haben!
