### ISSUE TITLE
Broadcasting: OOP & Threads

### ISSUE THREAD

**Issue by nico-osd** [nico-osd/osd_repo#8]
Folgende Verbesserungsvorschläge für Broadcasting, da hier seit Donnerstag die Zeit stehen blieb:

1. Implementieren des Broadcast Prototypen in OOP-Style
2. Implementieren als Thread
3. SocketServer + Handler Implementierung (?)

Mögliche Implementierung von [Multicast mit UDPServer](http://www.nealc.com/blog/blog/2012/09/11/testing/) + [PyDoc](https://docs.python.org/3.4/library/socketserver.html?highlight=baserequesthandler#socketserver-udpserver-example)

**Comment by MarkusWET** [comment]
Zeit ist nicht wirklich stehen geblieben, nur macht es aus meiner Sicht wenig Sinn rohen WIP-Code hochzuladen. Habs jetzt trotzdem mal gemacht - oop ist *ansatzweise* da, wird natürlich noch mehr und besser ;)

Cheers!

**Comment by nico-osd** [comment]
Ich habe die Issue geöffnet da ich heute an BC arbeiten will, da vieles davon abhängt und das Observer-Pattern prinzipiell fertig ist.

Ich möchte zusätzlich die Main-Methode/Klasse aus BC refactoren und als den globalen Startpunkt definieren. Dann können wir uns Gedanken zu Threading Bottom-Up machen.

Wie siehts aus?

**Comment by nico-osd** [comment]
Wie mit Chris heute besprochen, ich wollte ursprünglich mit BC bis morgen fertig sein. Durch unvorhergesehene Troubles mit anderen Tätigkeitsbereichen, wird es frühestens morgen. Die aktuellste Implementierung ist im branch feature-bc zu finden. Mit Chris habe ich über die Theorie bereits gesprochen. 

Das senden eines Multicastpakets erfordert keinen Thread (derzeitige Implementierung), welcher auf das Ack wartet, außer wir nutzen dies um nicht antwortende aus der Liste zu schmeissen / als möglicherweise offline zu markieren. Da dies jedoch aufwendiger erscheint und Team 4 wieder arbeitslos machen würde haben wir davon Abstand genommen.

Die weitere Vorgehensweise bzw. was noch zu tun ist in manager.py:

* Liste periodisch senden und time.sleep() verlängern, sobald ein Paket eines anderen Hosts einging, mittels callback.
* Liste serialisiert (Liste -> json) senden  
* Liste deserialisieren (json -> Liste)
* Sauberes schließen aller Threads (Multicast Receiver/Listener) bei beendigung

Im Zusammenhang mit #4, #5 und #7:

Die Implementierungen von `Observer` müssen sich irgendwie bei `UDPUpdateObseravable` anmelden können - da muss ich mir etwas überlegen. Möglich wäre es hier wieder über Callbacks, aber das scheint mir sehr unschön. Ein Singleton Pattern wäre auch hier (siehe Singleton in main.py) möglicherweise angebracht.
